from enum import Enum


class PostStatus(str, Enum):
    SAVED = 'SAVED'
    SCHEDULED = 'SCHEDULED'
    RESCHEDULED = 'RESCHEDULED'
    PUBLISHED = 'PUBLISHED'
    CANCELED = 'CANCELED'


class PostLoadFilter(str, Enum):
    SAVED = 'SAVED'
    SCHEDULED = 'SCHEDULED'
    RESCHEDULED = 'RESCHEDULED'
    PUBLISHED = 'PUBLISHED'
    CANCELED = 'CANCELED'
    ALL = 'ALL'
    NOTCANCELED = 'NOTCANCELED'
    NOTCANCELEDPUBLISHED = 'NOTCANCELEDPUBLISHED'
